version: "3.8"
services:
  rss2email:
    command: daemon -verbose steve@steve.fi
    entrypoint: rss2email
    environment:
    - SMTP_USERNAME=steve@example.com
    - SMTP_PASSWORD=blah.blah.blah!
    - SMTP_HOST=smtp.gmail.com
    restart: always
    image: skx/rss2email
    volumes:
    - /srv/rss2email/config/:/app/.rss2email/
